### ISSUE TITLE
Python Verison

### ISSUE THREAD

**Issue by EliteAspect21** [DevilGale/PokeCord#7]
What version of python does this bot run on?

**Comment by SyedAhkam** [comment]
Anything above 3.5 should be good.

**Comment by EliteAspect21** [comment]
@SyedAhkam Another problem has occured 
`Traceback (most recent call last):
File "main.py", line 1, in <module>
from Config import *
File "/home/container/Config.py", line 1, in <module>
from var_secrets import *
File "/home/container/var_secrets.py", line 4
CLIENT_SECRET = 1JLfLEC-_GtSf-maXj1t4FIIvcqmCJA2 #Discord given
SyntaxError: invalid syntax`

Yes, I did change the client secret

**Comment by SyedAhkam** [comment]
> @SyedAhkam Another problem has occured
> `Traceback (most recent call last): File "main.py", line 1, in <module> from Config import * File "/home/container/Config.py", line 1, in <module> from var_secrets import * File "/home/container/var_secrets.py", line 4 CLIENT_SECRET = 1JLfLEC-_GtSf-maXj1t4FIIvcqmCJA2 #Discord given SyntaxError: invalid syntax`
> 
> Yes, I did change the client secret

Wrap it inside quotes
