### ISSUE TITLE
Main.py isn't working

### ISSUE THREAD

**Issue by Arushbhai** [DevilGale/PokeCord#9]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/storage/emulated/0/Pokecord main/Config.py", line 32, in <module>
    imgr_client = ImgurClient(imgr_client_id, imgr_client_secret)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 85, in __init__
    self.credits = self.get_credits()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 94, in get_credits
    return self.make_request('GET', 'credits', None, True)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 127, in make_request
    header = self.prepare_headers(force_anon)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 111, in prepare_headers
    raise ImgurClientError('Client credentials not found!')
imgurpython.helpers.error.ImgurClientError: Client credentials not found!

[Program finished]

**Comment by SyedAhkam** [comment]
> Traceback (most recent call last):
>   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
>     start(fakepyfile,mainpyfile)
>   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
>     exec(open(mainpyfile).read(),  __main__.__dict__)
>   File "<string>", line 1, in <module>
>   File "/storage/emulated/0/Pokecord main/Config.py", line 32, in <module>
>     imgr_client = ImgurClient(imgr_client_id, imgr_client_secret)
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 85, in __init__
>     self.credits = self.get_credits()
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 94, in get_credits
>     return self.make_request('GET', 'credits', None, True)
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 127, in make_request
>     header = self.prepare_headers(force_anon)
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/imgurpython/client.py", line 111, in prepare_headers
>     raise ImgurClientError('Client credentials not found!')
> imgurpython.helpers.error.ImgurClientError: Client credentials not found!
> 
> [Program finished]

Set your credentials first in **var_secret.py** file as mentioned in the readme.
